import "./globals.css";
import type { Metadata } from "next";
import { Rubik, Syne, Inter } from "next/font/google";
import Nav from "@/components/ui/Nav";
import Footer from "@/components/ui/Footer";
import Wrapper from "@/providers/Wrapper";

const rubik = Rubik({
  variable: "--font-rubik",
  subsets: ["latin"],
});

const syne = Syne({
  variable: "--font-syne",
  subsets: ["latin"],
});

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${rubik.variable} ${syne.variable} ${inter.variable} antialiased bg-secondary-black text-secondary-white`}>
        <Wrapper>
            {children}
        </Wrapper>
      </body>
    </html>
  );
}
